# Generated by Django 3.0 on 2019-12-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_purpose', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BoardCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=200)),
                ('b_purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Board')),
            ],
        ),
    ]
