# Generated by Django 3.0 on 2019-12-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20191208_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
