# Generated by Django 3.0 on 2019-12-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20191208_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardcategory',
            name='id',
        ),
        migrations.AddField(
            model_name='boardcategory',
            name='c_name',
            field=models.CharField(default='a', max_length=200, primary_key=True, serialize=False),
        ),
    ]
