# Generated by Django 3.0 on 2019-12-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20191208_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_purpose',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='identifier',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='boardcategory',
            name='c_name',
            field=models.CharField(default='a', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='boardcategory',
            name='identifier',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
