# Generated by Django 3.0 on 2019-12-08 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20191208_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardCon',
            fields=[
                ('m_title', models.CharField(max_length=200)),
                ('m_create_date', models.DateTimeField(verbose_name='date created')),
                ('m_update_date', models.DateTimeField(verbose_name='date updated')),
                ('m_content', models.TextField()),
                ('identifier', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.BoardCategory')),
            ],
        ),
    ]
