# Generated by Django 3.0 on 2019-12-08 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_boardcon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcategory',
            name='b_purpose',
            field=models.ForeignKey(db_column='b_purpose', on_delete=django.db.models.deletion.CASCADE, to='community.Board', to_field='b_purpose'),
        ),
    ]
