# Generated by Django 3.0 on 2019-12-08 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_auto_20191209_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardcategory',
            name='b_purpose',
        ),
        migrations.AddField(
            model_name='boardcategory',
            name='refer',
            field=models.ForeignKey(db_column='refer', default=0, on_delete=django.db.models.deletion.CASCADE, to='community.Board'),
            preserve_default=False,
        ),
    ]
