# Generated by Django 2.2.6 on 2019-12-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_auto_20191209_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardcon',
            old_name='c_name',
            new_name='refer',
        ),
    ]
