# Generated by Django 2.2.6 on 2019-12-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_auto_20191210_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcon',
            name='m_WriterID',
            field=models.EmailField(default='1234@5678.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardcon',
            name='m_WriterName',
            field=models.CharField(default='이현우', max_length=30),
            preserve_default=False,
        ),
    ]
