# Generated by Django 2.2.6 on 2019-12-09 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_auto_20191210_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.MyUser'),
        ),
    ]
