# Generated by Django 2.2.6 on 2019-12-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_myuser_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='Grade',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
