# Generated by Django 2.2.6 on 2019-12-09 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_auto_20191210_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='tutor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.MyUser'),
        ),
    ]
