# Generated by Django 2.2.6 on 2019-12-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_auto_20191210_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='SN',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
