# Generated by Django 3.0 on 2019-12-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_auto_20191215_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='identifier',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='boardcategory',
            name='identifier',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='boardcon',
            name='identifier',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
