# Generated by Django 3.0 on 2019-12-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_auto_20191215_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcon',
            name='file_desc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boardcon',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d'),
        ),
    ]
